name: Check Build Status

env:
  # Change this to point to your solution, or the folder in which your solution 
  # can be found.
  SLN_PATH: Source/

on:
  push:
    branches:
      - master
      - develop
    paths:
      - Source/**
    tags-ignore:
      # This will ignore release versions tagged with a version identifier. We'll 
      # use a separate workflow for them.
      - 'v*'
    # If you don't want to build on a pull_request, then remove this, but it is 
    # kind of helpful.
  pull_request:
    paths: 
      - Source/

jobs:
  build:
    name: Build on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        # You can configure operating systems to build on here. It shouldn't make a difference 
        # operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        operating-system: [ubuntu-latest]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x.x

    - name: Build Mod 1.3
      run: dotnet build ${{ env.SLN_PATH }} --configuration v1.3

    - name: Build Mod 1.4
      run: dotnet build ${{ env.SLN_PATH }} --configuration v1.4
